services:
  yolo-flask:
    build: .
    image: yolo-flask-mongo:latest
    container_name: yolo-flask
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/yolo_db?authSource=admin
    volumes:
      - ./uploads:/app/uploads
      - ./model:/app/model:ro
    depends_on:
      - mongodb
    networks:
      - yolo-net

  mongodb:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: yolo_db
    volumes:
      - mongo-data:/data/db
    networks:
      - yolo-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - yolo-net

volumes:
  mongo-data:

networks:
  yolo-net:
    driver: bridge
